---
- name: Configure Node.js App
  hosts: nodejs_servers
  become: yes

  tasks:
    - name: Copy files from Jenkins workspace to odataProjects
      copy:
        src: /var/lib/jenkins/workspace/nodeJS_CRUD
        dest: /home/thyler/odataProjects/
        remote_src: true

    - name: Create service file
      template:
        src: nodeJS_CRUD.j2  
        dest: /etc/systemd/system/nodeJS_CRUD.service
      notify:
        - Reload systemd
        - Restart service

    - name: Start and enable service
      systemd:
        name: nodeJS_CRUD
        enabled: yes
        state: started

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Restart service
      systemd:
        name: nodeJS_CRUD
        state: restarted

    - name: Check if the database exists
      mysql_db:
        name: nodeJenkins
        state: present
      register: database_exists

    - name: Import database if it does not exist
      when: database_exists.changed
      mysql_db:
        name: nodeJenkins
        state: import
        target: /home/thyler/odataProjects/nodeJS_CRUD/database.sql

    - name: Copy .env.server contents to .env
      copy:
        src: /home/thyler/odataProjects/nodeJS_CRUD/.env.server
        dest: /home/thyler/odataProjects/nodeJS_CRUD/.env
        remote_src: true
